<?php

$menu = $this->_sysCfg->topmenu;
if(!$menu['enabled']) return;

// drawMainMenu vs DrowMobileMenu
$menuHtml = $this->drawMainMenu();
$mobileMenu = $menuHtml['mobile'];
$desktop 	= $menuHtml['desktop'];
$ids  = explode(',', $menu['notIncludeNav']);
foreach ($ids as $id) { unset($desktop[$id]); }
// drawHomeMenu
$drawHomeMenu = $menu['home'] ? $this->drawHomeMenu() : '';
// drawMainMenu
$drawMainMenu = $menu['mainCat'] ? implode("\n", $desktop) : '';
// drawExtMenu ExtraMenu
$drawExtraMenu = $menu['extraCat'] ? $this->drawExtraMenu() : '';
?>
<ul class="gsb-core-menu" >
    <?php echo $drawHomeMenu ?>
    <?php echo $mobileMenu ?>
    <?php echo $drawExtraMenu ?>
</ul>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function(){
            //the trigger on hover when cursor directed to this class
            $(".gsb-core-menu li").hover(
                function(){
                    //i used the parent ul to show submenu
                    $(this).children('ul').slideDown('fast');
                },
                //when the cursor away
                function () {
                    $('ul', this).slideUp('fast');
                });
            //this feature only show on 600px device width
            $(".gsb-hamburger-menu").click(function(){
                $(".gsb-burger-1, .gsb-burger-2, .gsb-burger-3").toggleClass("open");
                $(".gsb-core-menu").slideToggle("fast");
            });
        });
    });
    /** credit:@rafonzoo
     http://rafonzo.blogspot.co.id/ **/
</script>
