<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="block-search">
    <div class="block block-content">
        <form class="form minisearch form-search gsb-search-box search_mini_form" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <?php 
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $config = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('alothemes/categorysearch', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
                    $catalogsearch = isset($config['enabled']) ? $config['enabled'] : 0;
                    $depth       = isset($config['depth'])   ? $config['depth']   : 0;
          
                ?>
                <div>
                    <div class="">
                        <div class="gsb-content-search-desktop">
                            <input id="search"
                             data-mage-init='{"quickSearchAutocomplete":{
                                  "formSelector":"#search_mini_form",
                                  "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                  "destinationSelector":".search_autocomplete"}
                             }'
                             type="text"
                             name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                             value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                             placeholder=" "
                             class="input-text text gsb-search-input search gsb-input-search"
                             maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                             role="combobox"
                             aria-haspopup="false"
                             aria-autocomplete="both"
                             autocomplete="off"/>
                            <a href="javascript:void(0)" class="gsb-btn-search icon icon-search"></a>

                            <div class="control <?php echo $catalogsearch ? 'catalogsearch' : ''?>">
                              <div id="search_autocomplete" class="search-autocomplete search_autocomplete"></div>
                              <?php echo $block->getChildHtml() ?>
                              <?php if($catalogsearch) : ?>
                            </div>

                  <?php endif ?>
                </div>
            </div>
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search button" style="display: none;">
                    <span><span><i class="fa fa-search"></i><?php /* @escapeNotVerified */ echo __('Search'); ?></span></span>
                </button>
                </div>
            </div>
        </form>
    </div>
</div>

